# Generated by Django 5.2.10 on 2026-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_notes/'),
        ),
    ]
