# Generated by Django 5.2.10 on 2026-01-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_note_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='NoteAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='api_app.note')),
            ],
            options={
                'db_table': 'note_audios',
            },
        ),
    ]
