# Generated by Django 5.2.10 on 2026-01-18 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_note_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Task', 'Task'), ('Reminder', 'Reminder'), ('Shopping', 'Shopping'), ('Fact', 'Fact')], default='Task', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='api_app.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_items',
                'indexes': [models.Index(fields=['user', 'status'], name='action_item_user_id_e6acaa_idx'), models.Index(fields=['item_type'], name='action_item_item_ty_6bc6cc_idx')],
            },
        ),
    ]
