# Generated by Django 5.2.10 on 2026-01-18 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_actionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item_content', models.TextField()),
                ('item_type', models.CharField(max_length=20)),
                ('action_type', models.CharField(choices=[('Added by AI', 'Added by AI'), ('Manually Added', 'Manually Added'), ('Modified', 'Modified'), ('Status Changed', 'Status Changed'), ('Deleted', 'Deleted')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_item_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
