# Generated by Django 5.2.10 on 2026-01-18 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_actionitemhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemhistory',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_item_history', to='api_app.note'),
        ),
        migrations.AddField(
            model_name='actionitemhistory',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
