# Generated by Django 5.2.10 on 2026-01-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_actionitem_due_date_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='linked_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='api_app.alarm'),
        ),
    ]
