# Generated by Django 5.2.10 on 2026-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_actionitem_end_time_actionitem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='item_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Reminder', 'Reminder'), ('Shopping', 'Shopping'), ('Fact', 'Fact'), ('StudyNote', 'StudyNote')], default='Task', max_length=20),
        ),
    ]
