# Generated by Django 5.2.10 on 2026-01-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_document_documentchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='document',
        ),
        migrations.AddField(
            model_name='actionitem',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='item_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Reminder', 'Reminder'), ('Shopping', 'Shopping'), ('Fact', 'Fact'), ('StudyNote', 'StudyNote'), ('Habit', 'Habit')], default='Task', max_length=20),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='units', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api_app.habit')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.note')),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
